name: hr
description: "The HR app simplifies employee data management, allowing you to track info, manage leave requests, and generate secure reports easily."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # * For multi languages
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # * For preview to show in responsive design
  device_preview: ^1.2.0

  # * local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.4.1

  # * state management
  get: ^4.6.6

  # * for internet
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

  # * To make == operator
  equatable: ^2.0.5

  # * To get the place
  geolocator: ^13.0.1

  # * To get device info
  device_info_plus: ^11.0.0

  # * check if user open location or not
  permission_handler: ^11.3.1

  # * Notification in background
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
  arb_dir: assets/languages
  output_dir: lib/core/utils/config/locale/generated
